# Generated by Django 5.2 on 2025-05-08 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='client_general_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание файла')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Общий документ клиента',
                'verbose_name_plural': 'Общие документы клиентов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
