# Generated by Django 5.2 on 2025-05-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='title',
            field=models.CharField(default=1, help_text="Придумайте короткое и понятное название для этого документа (например, 'Скан паспорта', 'Договор аренды').", max_length=150, verbose_name='Название документа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание (необязательно)'),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='document',
            field=models.FileField(upload_to='client_general_documents/%Y/%m/%d/', verbose_name='Файл документа'),
        ),
    ]
