# Generated by Django 4.2 on 2025-02-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Ожидает подтверждения'), ('Approved', 'Подтверждено'), ('Rejected', 'Отклонено')], default='Pending', max_length=10, verbose_name='Статус'),
        ),
    ]
